parameters:
- name: environment
  type: string
- name: ServiceConnectionName
  type: string
- name: webappName
  type: string
jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: ${{ parameters.ServiceConnectionName }}
              appType: 'webAppLinux'
              appName: '${{ parameters.webappName }}'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'